# DROP TABLES

songplay_table_drop = "DROP TABLE IF EXISTS songsplay CASCADE;"
user_table_drop = "DROP TABLE IF EXISTS songs CASCADE;"
song_table_drop = "DROP TABLE IF EXISTS artists CASCADE;"
artist_table_drop = "DROP TABLE IF EXISTS time CASCADE;"
time_table_drop = "DROP TABLE IF EXISTS users CASCADE;"

# CREATE TABLES

user_table_create = ("""
    CREATE TABLE IF NOT EXISTS users (
        user_id INT GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR,
        last_name VARCHAR,
        gender boolean,
        PRIMARY KEY(user_id)
    );
""")

artist_table_create = ("""
    CREATE TABLE IF NOT EXISTS artists (
        artist_id INT GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR,
        location VARCHAR,
        latitude DECIMAL(10, 8),
        longitude DECIMAL(11, 8),
        PRIMARY KEY(artist_id)
    );
""")

time_table_create = ("""
CREATE TABLE IF NOT EXISTS time (
    start_time TIMESTAMP,
    day INTEGER,
    week INTEGER,
    month INTEGER,
    year INTEGER,
    weekday INTEGER
);
""")

song_table_create = ("""
    CREATE TABLE IF NOT EXISTS songs (
        song_id INT GENERATED BY DEFAULT AS IDENTITY,
        title VARCHAR,
        artist_id INT GENERATED BY DEFAULT AS IDENTITY,
        year INTEGER,
        duration INTEGER,
        PRIMARY KEY(song_id),
        FOREIGN KEY(artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE
    );
""")


songplay_table_create = ("""
    CREATE TABLE IF NOT EXISTS songplays (
        songplay_id INT GENERATED BY DEFAULT AS IDENTITY,
        user_id INT GENERATED BY DEFAULT AS IDENTITY,
        start_time TIMESTAMP,
        level VARCHAR,
        song_id INT GENERATED BY DEFAULT AS IDENTITY,
        artist_id INT GENERATED BY DEFAULT AS IDENTITY,
        session_id INT GENERATED BY DEFAULT AS IDENTITY,
        location VARCHAR,
        user_agent VARCHAR,
        FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
        FOREIGN KEY(song_id) REFERENCES songs(song_id) ON DELETE CASCADE,
        FOREIGN KEY(artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE
    );
""")

# INSERT RECORDS

songplay_table_insert = ("""
""")

user_table_insert = ("""
""")

song_table_insert = ("""
""")

artist_table_insert = ("""
""")

time_table_insert = ("""
""")

# FIND SONGS

song_select = ("""
""")

# QUERY LISTS

create_table_queries = [user_table_create, artist_table_create, time_table_create, song_table_create,
                        songplay_table_create]
drop_table_queries = [songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]
